/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Secure;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author d_virus
 */
public class dealerdet extends javax.swing.JFrame {

    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public dealerdet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dmobileno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dinsertbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ddeletebtn = new javax.swing.JButton();
        dsavebtn = new javax.swing.JButton();
        drefreshbtn = new javax.swing.JButton();
        did = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        daddress = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dtable = new javax.swing.JTable();
        dupdatebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(0, 255, 255));
        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Dealer Name          :");

        dname.setBackground(new java.awt.Color(153, 255, 255));
        dname.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setBackground(new java.awt.Color(0, 255, 255));
        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Dealer Address      :");

        dmobileno.setBackground(new java.awt.Color(153, 255, 255));
        dmobileno.setForeground(new java.awt.Color(0, 0, 0));
        dmobileno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dmobilenoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Dealer Mobile No. :");

        dinsertbtn.setBackground(new java.awt.Color(0, 153, 153));
        dinsertbtn.setForeground(new java.awt.Color(0, 0, 0));
        dinsertbtn.setText("INSERT");
        dinsertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dinsertbtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 255, 255));
        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("             DEALER DETAILS");

        ddeletebtn.setBackground(new java.awt.Color(0, 153, 153));
        ddeletebtn.setForeground(new java.awt.Color(0, 0, 0));
        ddeletebtn.setText("DELETE");
        ddeletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddeletebtnActionPerformed(evt);
            }
        });

        dsavebtn.setBackground(new java.awt.Color(0, 153, 153));
        dsavebtn.setForeground(new java.awt.Color(0, 0, 0));
        dsavebtn.setText("SAVE");
        dsavebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsavebtnActionPerformed(evt);
            }
        });

        drefreshbtn.setBackground(new java.awt.Color(0, 153, 153));
        drefreshbtn.setForeground(new java.awt.Color(0, 0, 0));
        drefreshbtn.setText("REFRESH");
        drefreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drefreshbtnActionPerformed(evt);
            }
        });

        did.setBackground(new java.awt.Color(153, 255, 255));
        did.setForeground(new java.awt.Color(0, 0, 0));
        did.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                didActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 255, 255));
        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Dealer ID                 :");

        daddress.setBackground(new java.awt.Color(153, 255, 255));
        daddress.setForeground(new java.awt.Color(0, 0, 0));
        daddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daddressActionPerformed(evt);
            }
        });

        dtable.setBackground(new java.awt.Color(153, 255, 255));
        dtable.setForeground(new java.awt.Color(255, 255, 255));
        dtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DEALER ID", "DEALER NAME", "DEALER ADDRESS", "DEALER MOBILE NO."
            }
        ));
        dtable.setGridColor(new java.awt.Color(204, 204, 204));
        dtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dtable);

        dupdatebtn.setBackground(new java.awt.Color(0, 153, 153));
        dupdatebtn.setForeground(new java.awt.Color(0, 0, 0));
        dupdatebtn.setText("UPDATE");
        dupdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dupdatebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dname)
                            .addComponent(did)
                            .addComponent(daddress)
                            .addComponent(dmobileno, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 114, 114)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dupdatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddeletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dinsertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dsavebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(drefreshbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(301, 301, 301))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drefreshbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(did, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dinsertbtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(ddeletebtn))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(dupdatebtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dmobileno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(dsavebtn))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void daddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daddressActionPerformed

    private void didActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_didActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_didActionPerformed

    private void dmobilenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dmobilenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dmobilenoActionPerformed

    private void dinsertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dinsertbtnActionPerformed
        // TODO add your handling code here:
        conn=MySqlConnect.ConnectDB();
        String sql= "INSERT INTO DEALERDET"
                    +"(did,dname,daddress,dmobileno)"
                    +"VALUES(?,?,?,?)";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1, did.getText());
            pst.setString(2, dname.getText());
            pst.setString(3, daddress.getText());
            pst.setString(4, dmobileno.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Successfully!");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_dinsertbtnActionPerformed

    private void ddeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddeletebtnActionPerformed
        // TODO add your handling code here:
        try{
            String id=did.getText();
            //String name=dname.getText();
            //String address=daddress.getText();
            //String mobileno=dmobileno.getText();
            conn=MySqlConnect.ConnectDB();
            String Sql="delete from dealerdet where did= '"+id+"' ";
            pst=conn.prepareStatement(Sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Record Deleted Successfully!");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }   
    }//GEN-LAST:event_ddeletebtnActionPerformed

    private void drefreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drefreshbtnActionPerformed
        // TODO add your handling code here:
        conn=MySqlConnect.ConnectDB();
        //String Sql="CALL DISP_DEALERDET";
        String Sql="select * from dealerdet";
        
        try{
            pst=conn.prepareStatement(Sql);
            rs=pst.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)dtable.getModel();
            tm.setRowCount(0);
            
            while(rs.next()){
                Object o[]={rs.getInt("did"),rs.getString("dname"),rs.getString("daddress"),rs.getInt("dmobileno")};
                tm.addRow(o);
                
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_drefreshbtnActionPerformed

    private void dsavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsavebtnActionPerformed
        // TODO add your handling code here:
        conn=MySqlConnect.ConnectDB();
        String Sql="COMMIT";
        try{
            pst=conn.prepareStatement(Sql);
            rs=pst.executeQuery();
            JOptionPane.showMessageDialog(null, "Record Saved successfully!");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_dsavebtnActionPerformed

    private void dtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtableMouseClicked
        // TODO add your handling code here:
        int selectedrow= dtable.getSelectedRow();
        DefaultTableModel dt= (DefaultTableModel)dtable.getModel();
        did.setText(dt.getValueAt(selectedrow, 0).toString());
        dname.setText(dt.getValueAt(selectedrow, 1).toString());
        daddress.setText(dt.getValueAt(selectedrow, 2).toString());
        dmobileno.setText(dt.getValueAt(selectedrow, 3).toString());
    }//GEN-LAST:event_dtableMouseClicked

    private void dupdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dupdatebtnActionPerformed
        // TODO add your handling code here:
        try{
            String id=did.getText();
            String name=dname.getText();
            String address=daddress.getText();
            String mobileno=dmobileno.getText();
            conn=MySqlConnect.ConnectDB();
            String Sql="update dealerdet set did = '"+id+"' ,dname= '"+name+"' ,daddress = '"+address+"' ,dmobileno='"+mobileno+"' where did='"+id+"' or dname='"+name+"' ";
            pst=conn.prepareStatement(Sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Record Updated Successfully!");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_dupdatebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dealerdet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dealerdet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dealerdet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dealerdet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dealerdet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField daddress;
    private javax.swing.JButton ddeletebtn;
    private javax.swing.JTextField did;
    private javax.swing.JButton dinsertbtn;
    private javax.swing.JTextField dmobileno;
    private javax.swing.JTextField dname;
    private javax.swing.JButton drefreshbtn;
    private javax.swing.JButton dsavebtn;
    private javax.swing.JTable dtable;
    private javax.swing.JButton dupdatebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
