/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Secure;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author d_virus
 */
public class staffdet extends javax.swing.JFrame {

    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public staffdet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        sdeletebtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        srefreshbtn = new javax.swing.JButton();
        sname = new javax.swing.JTextField();
        supdatebtn = new javax.swing.JButton();
        smobileno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        stable = new javax.swing.JTable();
        sinsertbtn = new javax.swing.JButton();
        ssavebtn = new javax.swing.JButton();
        saddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Staff Name          :");

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Staff ID                 :");

        sid.setBackground(new java.awt.Color(51, 51, 51));
        sid.setForeground(new java.awt.Color(255, 255, 255));

        sdeletebtn.setBackground(new java.awt.Color(0, 0, 0));
        sdeletebtn.setForeground(new java.awt.Color(255, 255, 255));
        sdeletebtn.setText("DELETE");
        sdeletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdeletebtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("              STAFF DETAILS");

        srefreshbtn.setBackground(new java.awt.Color(0, 0, 0));
        srefreshbtn.setForeground(new java.awt.Color(255, 255, 255));
        srefreshbtn.setText("REFRESH");
        srefreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srefreshbtnActionPerformed(evt);
            }
        });

        sname.setBackground(new java.awt.Color(51, 51, 51));
        sname.setForeground(new java.awt.Color(255, 255, 255));

        supdatebtn.setBackground(new java.awt.Color(0, 0, 0));
        supdatebtn.setForeground(new java.awt.Color(255, 255, 255));
        supdatebtn.setText("UPDATE");
        supdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supdatebtnActionPerformed(evt);
            }
        });

        smobileno.setBackground(new java.awt.Color(51, 51, 51));
        smobileno.setForeground(new java.awt.Color(255, 255, 255));

        stable.setBackground(new java.awt.Color(102, 102, 102));
        stable.setForeground(new java.awt.Color(255, 255, 255));
        stable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STAFF ID", "STAFF NAME", "STAFF ADRRESS", "STAFF MOBILE NO."
            }
        ));
        stable.setGridColor(new java.awt.Color(255, 255, 255));
        stable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        stable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stable);

        sinsertbtn.setBackground(new java.awt.Color(0, 0, 0));
        sinsertbtn.setForeground(new java.awt.Color(255, 255, 255));
        sinsertbtn.setText("INSERT");
        sinsertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinsertbtnActionPerformed(evt);
            }
        });

        ssavebtn.setBackground(new java.awt.Color(0, 0, 0));
        ssavebtn.setForeground(new java.awt.Color(255, 255, 255));
        ssavebtn.setText("SAVE");
        ssavebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssavebtnActionPerformed(evt);
            }
        });

        saddress.setBackground(new java.awt.Color(51, 51, 51));
        saddress.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Staff Address       :");

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Staff Mobile no. :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(srefreshbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(288, 288, 288))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saddress, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(smobileno, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sinsertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sdeletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supdatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ssavebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(srefreshbtn)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sinsertbtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdeletebtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(saddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supdatebtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(smobileno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssavebtn))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sdeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdeletebtnActionPerformed
        // TODO add your handling code here:
        try{
            String id=sid.getText();
            String name=sname.getText();
            String address=saddress.getText();
            String mobileno=smobileno.getText();
            conn=MySqlConnect.ConnectDB();
            String Sql="delete from staffdet where sid= '"+id+"' ";
            pst=conn.prepareStatement(Sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Record Deleted Successfully!");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }   
    }//GEN-LAST:event_sdeletebtnActionPerformed

    private void sinsertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinsertbtnActionPerformed
        // TODO add your handling code here:
        conn=MySqlConnect.ConnectDB();
        String sql= "INSERT INTO STAFFDET"
                    +"(sid,sname,saddress,smobileno)"
                    +"VALUES(?,?,?,?)";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1, sid.getText());
            pst.setString(2, sname.getText());
            pst.setString(3, saddress.getText());
            pst.setString(4, smobileno.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Successfully!");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_sinsertbtnActionPerformed

    private void stableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stableMouseClicked
        // TODO add your handling code here:
        int selectedrow= stable.getSelectedRow();
        DefaultTableModel dt= (DefaultTableModel)stable.getModel();
        sid.setText(dt.getValueAt(selectedrow, 0).toString());
        sname.setText(dt.getValueAt(selectedrow, 1).toString());
        saddress.setText(dt.getValueAt(selectedrow, 2).toString());
        smobileno.setText(dt.getValueAt(selectedrow, 3).toString());
    }//GEN-LAST:event_stableMouseClicked

    private void supdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supdatebtnActionPerformed
        // TODO add your handling code here:
        try{
            String id=sid.getText();
            String name=sname.getText();
            String address=saddress.getText();
            String mobileno=smobileno.getText();
            conn=MySqlConnect.ConnectDB();
            String Sql="update staffdet set sid = '"+id+"' ,sname= '"+name+"' ,saddress = '"+address+"' ,smobileno='"+mobileno+"' where sid='"+id+"' or sname='"+name+"' ";
            pst=conn.prepareStatement(Sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Record Updated Successfully!");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_supdatebtnActionPerformed

    private void ssavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssavebtnActionPerformed
        // TODO add your handling code here:
        conn=MySqlConnect.ConnectDB();
        String Sql="COMMIT";
        try{
            pst=conn.prepareStatement(Sql);
            rs=pst.executeQuery();
            JOptionPane.showMessageDialog(null, "Record Saved successfully!");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ssavebtnActionPerformed

    private void srefreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srefreshbtnActionPerformed
        // TODO add your handling code here:
        conn=MySqlConnect.ConnectDB();
        String Sql="CALL DISP_STAFFDET";
        try{
            pst=conn.prepareStatement(Sql);
            rs=pst.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)stable.getModel();
            tm.setRowCount(0);
            
            while(rs.next()){
                Object o[]={rs.getInt("sid"),rs.getString("sname"),rs.getString("saddress"),rs.getInt("smobileno")};
                tm.addRow(o);
                
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_srefreshbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staffdet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staffdet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staffdet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staffdet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staffdet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField saddress;
    private javax.swing.JButton sdeletebtn;
    private javax.swing.JTextField sid;
    private javax.swing.JButton sinsertbtn;
    private javax.swing.JTextField smobileno;
    private javax.swing.JTextField sname;
    private javax.swing.JButton srefreshbtn;
    private javax.swing.JButton ssavebtn;
    private javax.swing.JTable stable;
    private javax.swing.JButton supdatebtn;
    // End of variables declaration//GEN-END:variables
}
