/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Secure;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author d_virus
 */
public class vehdet extends javax.swing.JFrame {

  
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public vehdet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        vcreatedate = new javax.swing.JTextField();
        vid = new javax.swing.JTextField();
        vdeletebtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        vrefreshbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vtable = new javax.swing.JTable();
        vcost = new javax.swing.JTextField();
        vinsertbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        vmodel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        vname = new javax.swing.JTextField();
        vsavebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        vupdatebtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        vdesc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        did = new javax.swing.JTextField();
        cid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Car Model         :");

        vcreatedate.setBackground(new java.awt.Color(51, 51, 51));
        vcreatedate.setForeground(new java.awt.Color(255, 255, 255));

        vid.setBackground(new java.awt.Color(51, 51, 51));
        vid.setForeground(new java.awt.Color(255, 255, 255));
        vid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vidActionPerformed(evt);
            }
        });

        vdeletebtn.setBackground(new java.awt.Color(0, 0, 0));
        vdeletebtn.setForeground(new java.awt.Color(255, 255, 255));
        vdeletebtn.setText("DELETE");
        vdeletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vdeletebtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Car Cost           :");

        vrefreshbtn.setBackground(new java.awt.Color(0, 0, 0));
        vrefreshbtn.setForeground(new java.awt.Color(255, 255, 255));
        vrefreshbtn.setText("REFRESH");
        vrefreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vrefreshbtnActionPerformed(evt);
            }
        });

        vtable.setBackground(new java.awt.Color(102, 102, 102));
        vtable.setForeground(new java.awt.Color(255, 255, 255));
        vtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CAR ID", "CAR NAME", "CAR MODEL", "CAR COST", "CAR CREATE-DATE", "CAR DESCRIPTION", "DEALER ID", "CUSTOMER ID"
            }
        ));
        vtable.setGridColor(new java.awt.Color(204, 204, 204));
        vtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(vtable);

        vcost.setBackground(new java.awt.Color(51, 51, 51));
        vcost.setForeground(new java.awt.Color(255, 255, 255));

        vinsertbtn.setBackground(new java.awt.Color(0, 0, 0));
        vinsertbtn.setForeground(new java.awt.Color(255, 255, 255));
        vinsertbtn.setText("INSERT");
        vinsertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vinsertbtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Create-Date(yyyy-mm-dd) :");

        vmodel.setBackground(new java.awt.Color(51, 51, 51));
        vmodel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Car ID              :");

        vname.setBackground(new java.awt.Color(51, 51, 51));
        vname.setForeground(new java.awt.Color(255, 255, 255));

        vsavebtn.setBackground(new java.awt.Color(0, 0, 0));
        vsavebtn.setForeground(new java.awt.Color(255, 255, 255));
        vsavebtn.setText("SAVE");
        vsavebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vsavebtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("         VEHICLE DETAILS");

        vupdatebtn.setBackground(new java.awt.Color(0, 0, 0));
        vupdatebtn.setForeground(new java.awt.Color(255, 255, 255));
        vupdatebtn.setText("UPDATE");
        vupdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vupdatebtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Car Name         :");

        jLabel7.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Car Description  :");

        vdesc.setBackground(new java.awt.Color(51, 51, 51));
        vdesc.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Dealer ID              :");

        jLabel9.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Customer ID         :");

        did.setBackground(new java.awt.Color(51, 51, 51));
        did.setForeground(new java.awt.Color(255, 255, 255));

        cid.setBackground(new java.awt.Color(51, 51, 51));
        cid.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(219, 219, 219))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(vdesc, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(vcreatedate)
                                    .addComponent(did)
                                    .addComponent(cid)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)))
                                .addGap(73, 73, 73)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(vcost, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(vname)
                                    .addComponent(vmodel)
                                    .addComponent(vid))
                                .addGap(52, 52, 52)
                                .addComponent(vinsertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vsavebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vdeletebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103)
                        .addComponent(vupdatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(vrefreshbtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vrefreshbtn)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(vname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(vcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vinsertbtn)
                            .addComponent(vdeletebtn)
                            .addComponent(vupdatebtn))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(vcreatedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel7))
                            .addComponent(vdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(vsavebtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(did, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vinsertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vinsertbtnActionPerformed
        // TODO add your handling code here:
        conn=MySqlConnect.ConnectDB();
        String sql= "INSERT INTO VEHICLEDET"
                    +"(vid,vname,vcost,vmodel,vcreatedate,vdesc,did,cid)"
                    +"VALUES(?,?,?,?,?,?,?,?)";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1, vid.getText());
            pst.setString(2, vname.getText());
            pst.setString(3, vcost.getText());
            pst.setString(4, vmodel.getText());
            pst.setString(5, vcreatedate.getText());
            pst.setString(6, vdesc.getText());
            pst.setString(7, did.getText());
            pst.setString(8, cid.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Successfully!");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_vinsertbtnActionPerformed

    private void vdeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vdeletebtnActionPerformed
        // TODO add your handling code here:
        try{
            String id=vid.getText();
            //String name=vname.getText();
            //String cost=vcost.getText();
            //String model=vmodel.getText();
            //String createdate=vcreatedate.getText();
            //String desc=vdesc.getText();
            conn=MySqlConnect.ConnectDB();
            String Sql="delete from vehicledet where vid= '"+id+"' ";
            pst=conn.prepareStatement(Sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Record Deleted Successfully!");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }   
    }//GEN-LAST:event_vdeletebtnActionPerformed

    private void vtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vtableMouseClicked
        // TODO add your handling code here:
        int selectedrow= vtable.getSelectedRow();
        DefaultTableModel dt= (DefaultTableModel)vtable.getModel();
        vid.setText(dt.getValueAt(selectedrow, 0).toString());
        vname.setText(dt.getValueAt(selectedrow, 1).toString());
        vcost.setText(dt.getValueAt(selectedrow, 2).toString());
        vmodel.setText(dt.getValueAt(selectedrow, 3).toString());
        vcreatedate.setText(dt.getValueAt(selectedrow, 4).toString());
        vdesc.setText(dt.getValueAt(selectedrow, 5).toString());
        did.setText(dt.getValueAt(selectedrow, 0).toString());
        cid.setText(dt.getValueAt(selectedrow, 0).toString());
        
    }//GEN-LAST:event_vtableMouseClicked

    private void vupdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vupdatebtnActionPerformed
        // TODO add your handling code here:
        try{
            String id=vid.getText();
            String name=vname.getText();
            String cost=vcost.getText();
            String model=vmodel.getText();
            String createdate=vcreatedate.getText();
            String desc=vdesc.getText();
            String dlid=did.getText();
            String cuid=cid.getText();
            conn=MySqlConnect.ConnectDB();
            String Sql="update vehicledet set vid = '"+id+"' ,vname= '"+name+"' ,vcost = '"+cost+"' ,vmodel='"+model+"',vcreatedate='"+createdate+"',vdesc='"+desc+"',did='"+dlid+"',cid='"+cuid+"'  where vid='"+id+"' and vname='"+name+"' ";
            pst=conn.prepareStatement(Sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Record Updated Successfully!");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_vupdatebtnActionPerformed

    private void vsavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vsavebtnActionPerformed
        // TODO add your handling code here:
        conn=MySqlConnect.ConnectDB();
        String Sql="COMMIT";
        try{
            pst=conn.prepareStatement(Sql);
            rs=pst.executeQuery();
            JOptionPane.showMessageDialog(null, "Record Saved successfully!");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_vsavebtnActionPerformed

    private void vrefreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vrefreshbtnActionPerformed
        // TODO add your handling code here:
        conn=MySqlConnect.ConnectDB();
        String Sql="CALL DISP_VEHICLEDET";
        try{
            pst=conn.prepareStatement(Sql);
            rs=pst.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)vtable.getModel();
            tm.setRowCount(0);
            
            while(rs.next()){
                Object o[]={rs.getInt("vid"),rs.getString("vname"),rs.getInt("vcost"),rs.getString("vmodel"),rs.getDate("vcreatedate"),rs.getString("vdesc"),rs.getInt("did"),rs.getInt("cid")};
                tm.addRow(o);
                
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_vrefreshbtnActionPerformed

    private void vidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vehdet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vehdet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vehdet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vehdet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vehdet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cid;
    private javax.swing.JTextField did;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField vcost;
    private javax.swing.JTextField vcreatedate;
    private javax.swing.JButton vdeletebtn;
    private javax.swing.JTextField vdesc;
    private javax.swing.JTextField vid;
    private javax.swing.JButton vinsertbtn;
    private javax.swing.JTextField vmodel;
    private javax.swing.JTextField vname;
    private javax.swing.JButton vrefreshbtn;
    private javax.swing.JButton vsavebtn;
    private javax.swing.JTable vtable;
    private javax.swing.JButton vupdatebtn;
    // End of variables declaration//GEN-END:variables
}
