/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Secure;

/**
 *
 * @author d_virus
 */
public class welcome extends javax.swing.JFrame {

    /**
     * Creates new form welcome
     */
    public welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dealerdet = new javax.swing.JButton();
        custdet = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        vehdet = new javax.swing.JButton();
        staffdet = new javax.swing.JButton();
        cvsbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        dealerdet.setBackground(new java.awt.Color(51, 51, 51));
        dealerdet.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        dealerdet.setText("DEALER DETAILS");
        dealerdet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dealerdetActionPerformed(evt);
            }
        });

        custdet.setBackground(new java.awt.Color(51, 51, 51));
        custdet.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        custdet.setText("CUSTOMER DETAILS");
        custdet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custdetActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("    CAR SHOWROOM MANAGEMENT SYSTEM");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        vehdet.setBackground(new java.awt.Color(51, 51, 51));
        vehdet.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        vehdet.setText("VEHICLE DETAILS");
        vehdet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehdetActionPerformed(evt);
            }
        });

        staffdet.setBackground(new java.awt.Color(51, 51, 51));
        staffdet.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        staffdet.setText("STAFF DETAILS");
        staffdet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffdetActionPerformed(evt);
            }
        });

        cvsbtn.setBackground(new java.awt.Color(51, 51, 51));
        cvsbtn.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        cvsbtn.setText("CUSTOMER,VEHICLE,STAFF DETAILS");
        cvsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvsbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cvsbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(custdet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(staffdet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vehdet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dealerdet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(dealerdet)
                .addGap(18, 18, 18)
                .addComponent(vehdet)
                .addGap(18, 18, 18)
                .addComponent(staffdet)
                .addGap(18, 18, 18)
                .addComponent(custdet)
                .addGap(18, 18, 18)
                .addComponent(cvsbtn)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dealerdetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dealerdetActionPerformed
        // TODO add your handling code here:
        dealerdet dd=new dealerdet();
        dd.setVisible(true);
    }//GEN-LAST:event_dealerdetActionPerformed

    private void vehdetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehdetActionPerformed
        // TODO add your handling code here:
        vehdet vd=new vehdet();
        vd.setVisible(true);
    }//GEN-LAST:event_vehdetActionPerformed

    private void staffdetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffdetActionPerformed
        // TODO add your handling code here:
        staffdet sd=new staffdet();
        sd.setVisible(true);
    }//GEN-LAST:event_staffdetActionPerformed

    private void custdetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custdetActionPerformed
        // TODO add your handling code here:
      
        custdet cd=new custdet();
        cd.setVisible(true);
    }//GEN-LAST:event_custdetActionPerformed

    private void cvsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvsbtnActionPerformed
        // TODO add your handling code here:
        cvsdet cvs=new cvsdet();
        cvs.setVisible(true);
    }//GEN-LAST:event_cvsbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton custdet;
    private javax.swing.JButton cvsbtn;
    private javax.swing.JButton dealerdet;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton staffdet;
    private javax.swing.JButton vehdet;
    // End of variables declaration//GEN-END:variables
}
